[package]
name = "redis-stream-reactor"
version = "0.0.1-beta.21"
edition = "2021"
description = "Redis consumer group reactor"
readme = "./README.md"
license = "MIT"
repository = "https://github.com/Bajix/redis-stream-reactor/"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
async-trait = "0.1.51"
backoff = { version = "0.4.0", features = ["tokio"] }
env-url = "1.0.3"
futures = "0.3.17"
log = "0.4.14"
rand = "0.8.4"
redis = { version = "0.21.4", features = ["aio", "tokio-comp"] }
redis-swapplex = "0.1.2"
thiserror = "1.0.30"
tokio = { version = "1", features = ["macros", "signal"] }
